### ISSUE TITLE
crash when the port is already in use

### ISSUE THREAD

**Issue by fredericosilva** [wqweto/VbVncServer#1]
Great project,

I was looking for something simple like this to provide quick support.

I'm getting this error if the port is already in use.

![image](https://user-images.githubusercontent.com/927601/111882201-3c101800-89ac-11eb-8cf9-7fd787656f14.png)

**Comment by wqweto** [comment]
Hi,

If the listener port is already open there is no way to successfully start the VNC server on it before making it available again. (Just making sure your expectation are reasonable.)

I fixed `LastError` property to return human readable messages in commit 9401e34f0630eed33aa877b5f81fbf908c7418d1 so now the error in your case should be

```
---------------------------
VbVncServer
---------------------------
Only one usage of each socket address (protocol/network address/port) is normally permitted.
---------------------------
OK   
---------------------------
```

**Comment by fredericosilva** [comment]
It's way better 👍 Tks

![image](https://user-images.githubusercontent.com/927601/111920491-3affe900-8a87-11eb-8da4-6ded3a17eb6c.png)
