### ISSUE TITLE
Windows Virus & thread protection: false positive

### ISSUE THREAD

**Issue by fredericosilva** [wqweto/VbVncServer#2]
Hello,

While trying to connect to the app (v0.0.2) I received an alert from windows AV (Trojan:Win32/Wacatac.B!ml)

![image](https://user-images.githubusercontent.com/927601/111921026-486aa280-8a8a-11eb-8c6a-5823024cd255.png)

VirusTotal reports nothing
https://www.virustotal.com/gui/url/a1cf1634e818f41290386ab2f941d22febd325f931593e7f179c611805e68635/detection

Have you experienced something similar?

**Comment by fredericosilva** [comment]
Chrome shows this now: 

![image](https://user-images.githubusercontent.com/927601/111921470-adbf9300-8a8c-11eb-932a-1015c6f04027.png)

Running from source works fine

**Comment by wqweto** [comment]
This happens all the time with VB6 executables if they are small enough and not digitally signed.

You can compile the test project from the sources and hex compare it with the flagged download. Could be I am spreading viruses from my dev machine but I highly doubt it as it has never happened in the past 25 years.

I was thinking about setting up azure pipelines on the repo with automatic builds incl. signing the binary of the test project but its not worth it as the repo’s main purpose is about a single-class VNC server source code not a quickly cobbled up test executable.

**Comment by fredericosilva** [comment]
Thank you for the explanation.

Windows stopped complaining about v0.0.2 and v0.0.3 is fine.
So it was really a false positive.

Going to close the issue.
